@host = https://localhost:5001
@accessToken = {{login.response.body.$.accessToken}}

@refreshToken = {{login.response.body.$.refreshToken}}


### Register a new user

POST {{host}}/account/register HTTP/1.1
Content-Type: application/json

{
  "username": "andrew@example.com",
  "password": "SuperSecret1!",
  "email": "andrew@example.com"
}

###

# @name login 
POST {{host}}/account/login HTTP/1.1
Content-Type: application/json

{
  "email": "andrew@example.com",
  "password": "SuperSecret1!"
}

###

### Fetch a new access token
POST {{host}}/account/refresh HTTP/1.1
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###

GET {{host}}/weatherforecast/
Accept: application/json

###

GET {{host}}/weatherforecast/ HTTP/1.1
Accept: application/json
Authorization: Bearer {{accessToken}}





